"""Seed coding questions with test cases into the questions table.
Run: python seeds/seed_questions.py
"""
import asyncio, sys, os, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sqlalchemy import text
from app.core.database import AsyncSessionLocal

QUESTIONS = [
    {
        "title": "Two Sum",
        "difficulty": "easy",
        "problem_statement": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.",
        "constraints": "2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9\nOnly one valid answer exists.",
        "input_format": "First line: space-separated integers (the array)\nSecond line: integer target",
        "output_format": "Two space-separated integers (the indices)",
        "sample_input_1": "2 7 11 15\n9",
        "sample_output_1": "0 1",
        "sample_input_2": "3 2 4\n6",
        "sample_output_2": "1 2",
        "test_cases": json.dumps([
            {"input": "2 7 11 15\n9", "expected_output": "0 1"},
            {"input": "3 2 4\n6", "expected_output": "1 2"},
            {"input": "3 3\n6", "expected_output": "0 1"},
            {"input": "1 2 3 4 5\n9", "expected_output": "3 4"},
        ]),
        "tags": json.dumps(["array", "hash-table"]),
    },
    {
        "title": "Reverse a String",
        "difficulty": "easy",
        "problem_statement": "Write a function that reverses a string. The input string is given as an array of characters s.\n\nYou must do this by modifying the input array in-place with O(1) extra memory.",
        "constraints": "1 <= s.length <= 10^5\ns[i] is a printable ASCII character.",
        "input_format": "A single string",
        "output_format": "The reversed string",
        "sample_input_1": "hello",
        "sample_output_1": "olleh",
        "sample_input_2": "Hannah",
        "sample_output_2": "hannaH",
        "test_cases": json.dumps([
            {"input": "hello", "expected_output": "olleh"},
            {"input": "Hannah", "expected_output": "hannaH"},
            {"input": "a", "expected_output": "a"},
            {"input": "abcde", "expected_output": "edcba"},
        ]),
        "tags": json.dumps(["string", "two-pointers"]),
    },
    {
        "title": "Valid Parentheses",
        "difficulty": "easy",
        "problem_statement": "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n\nAn input string is valid if:\n- Open brackets must be closed by the same type of brackets.\n- Open brackets must be closed in the correct order.\n- Every close bracket has a corresponding open bracket of the same type.",
        "constraints": "1 <= s.length <= 10^4\ns consists of parentheses only '()[]{}'.",
        "input_format": "A string of bracket characters",
        "output_format": "true or false",
        "sample_input_1": "()",
        "sample_output_1": "true",
        "sample_input_2": "()[]{}", 
        "sample_output_2": "true",
        "test_cases": json.dumps([
            {"input": "()", "expected_output": "true"},
            {"input": "()[]{}", "expected_output": "true"},
            {"input": "(]", "expected_output": "false"},
            {"input": "([)]", "expected_output": "false"},
            {"input": "{[]}", "expected_output": "true"},
        ]),
        "tags": json.dumps(["stack", "string"]),
    },
    {
        "title": "FizzBuzz",
        "difficulty": "easy",
        "problem_statement": "Given an integer n, return a string array answer where:\n- answer[i] == 'FizzBuzz' if i is divisible by 3 and 5.\n- answer[i] == 'Fizz' if i is divisible by 3.\n- answer[i] == 'Buzz' if i is divisible by 5.\n- answer[i] == i (as a string) if none of the above conditions are true.\n\nNote: i is 1-indexed.",
        "constraints": "1 <= n <= 10^4",
        "input_format": "A single integer n",
        "output_format": "Space-separated strings for i from 1 to n",
        "sample_input_1": "3",
        "sample_output_1": "1 2 Fizz",
        "sample_input_2": "5",
        "sample_output_2": "1 2 Fizz 4 Buzz",
        "test_cases": json.dumps([
            {"input": "3", "expected_output": "1 2 Fizz"},
            {"input": "5", "expected_output": "1 2 Fizz 4 Buzz"},
            {"input": "15", "expected_output": "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz"},
        ]),
        "tags": json.dumps(["math", "string", "simulation"]),
    },
    {
        "title": "Palindrome Number",
        "difficulty": "easy",
        "problem_statement": "Given an integer x, return true if x is a palindrome, and false otherwise.\n\nAn integer is a palindrome when it reads the same forward and backward. For example, 121 is a palindrome while 123 is not.",
        "constraints": "-2^31 <= x <= 2^31 - 1",
        "input_format": "A single integer",
        "output_format": "true or false",
        "sample_input_1": "121",
        "sample_output_1": "true",
        "sample_input_2": "-121",
        "sample_output_2": "false",
        "test_cases": json.dumps([
            {"input": "121", "expected_output": "true"},
            {"input": "-121", "expected_output": "false"},
            {"input": "10", "expected_output": "false"},
            {"input": "1221", "expected_output": "true"},
            {"input": "0", "expected_output": "true"},
        ]),
        "tags": json.dumps(["math"]),
    },
    {
        "title": "Best Time to Buy and Sell Stock",
        "difficulty": "easy",
        "problem_statement": "You are given an array prices where prices[i] is the price of a given stock on the ith day.\n\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\n\nReturn the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.",
        "constraints": "1 <= prices.length <= 10^5\n0 <= prices[i] <= 10^4",
        "input_format": "Space-separated integers (prices)",
        "output_format": "A single integer (max profit)",
        "sample_input_1": "7 1 5 3 6 4",
        "sample_output_1": "5",
        "sample_input_2": "7 6 4 3 1",
        "sample_output_2": "0",
        "test_cases": json.dumps([
            {"input": "7 1 5 3 6 4", "expected_output": "5"},
            {"input": "7 6 4 3 1", "expected_output": "0"},
            {"input": "1 2", "expected_output": "1"},
            {"input": "2 4 1 7", "expected_output": "6"},
        ]),
        "tags": json.dumps(["array", "dynamic-programming"]),
    },
    {
        "title": "Longest Substring Without Repeating Characters",
        "difficulty": "medium",
        "problem_statement": "Given a string s, find the length of the longest substring without repeating characters.",
        "constraints": "0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.",
        "input_format": "A single string",
        "output_format": "A single integer",
        "sample_input_1": "abcabcbb",
        "sample_output_1": "3",
        "sample_input_2": "bbbbb",
        "sample_output_2": "1",
        "test_cases": json.dumps([
            {"input": "abcabcbb", "expected_output": "3"},
            {"input": "bbbbb", "expected_output": "1"},
            {"input": "pwwkew", "expected_output": "3"},
            {"input": "", "expected_output": "0"},
            {"input": "dvdf", "expected_output": "3"},
        ]),
        "tags": json.dumps(["hash-table", "string", "sliding-window"]),
    },
    {
        "title": "Add Two Numbers",
        "difficulty": "medium",
        "problem_statement": "You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.\n\nFor this problem, represent the linked list as a space-separated sequence of digits.",
        "constraints": "The number of nodes in each linked list is in the range [1, 100].\n0 <= Node.val <= 9\nIt is guaranteed that the list represents a number that does not have leading zeros.",
        "input_format": "First line: space-separated digits of first number (reversed)\nSecond line: space-separated digits of second number (reversed)",
        "output_format": "Space-separated digits of the sum (reversed)",
        "sample_input_1": "2 4 3\n5 6 4",
        "sample_output_1": "7 0 8",
        "sample_input_2": "0\n0",
        "sample_output_2": "0",
        "test_cases": json.dumps([
            {"input": "2 4 3\n5 6 4", "expected_output": "7 0 8"},
            {"input": "0\n0", "expected_output": "0"},
            {"input": "9 9 9 9 9 9 9\n9 9 9 9", "expected_output": "8 9 9 9 0 0 0 1"},
        ]),
        "tags": json.dumps(["linked-list", "math", "recursion"]),
    },
    {
        "title": "3Sum",
        "difficulty": "medium",
        "problem_statement": "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, j != k, and nums[i] + nums[j] + nums[k] == 0.\n\nNotice that the solution set must not contain duplicate triplets.",
        "constraints": "3 <= nums.length <= 3000\n-10^5 <= nums[i] <= 10^5",
        "input_format": "Space-separated integers",
        "output_format": "Each triplet on a new line, sorted within triplet, triplets sorted lexicographically. 'none' if no solution.",
        "sample_input_1": "-1 0 1 2 -1 -4",
        "sample_output_1": "-1 -1 2\n-1 0 1",
        "sample_input_2": "0 1 1",
        "sample_output_2": "none",
        "test_cases": json.dumps([
            {"input": "-1 0 1 2 -1 -4", "expected_output": "-1 -1 2\n-1 0 1"},
            {"input": "0 1 1", "expected_output": "none"},
            {"input": "0 0 0", "expected_output": "0 0 0"},
        ]),
        "tags": json.dumps(["array", "two-pointers", "sorting"]),
    },
    {
        "title": "Container With Most Water",
        "difficulty": "medium",
        "problem_statement": "You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\n\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\n\nReturn the maximum amount of water a container can store.",
        "constraints": "n == height.length\n2 <= n <= 10^5\n0 <= height[i] <= 10^4",
        "input_format": "Space-separated integers (heights)",
        "output_format": "A single integer (max water)",
        "sample_input_1": "1 8 6 2 5 4 8 3 7",
        "sample_output_1": "49",
        "sample_input_2": "1 1",
        "sample_output_2": "1",
        "test_cases": json.dumps([
            {"input": "1 8 6 2 5 4 8 3 7", "expected_output": "49"},
            {"input": "1 1", "expected_output": "1"},
            {"input": "4 3 2 1 4", "expected_output": "16"},
            {"input": "1 2 1", "expected_output": "2"},
        ]),
        "tags": json.dumps(["array", "two-pointers", "greedy"]),
    },
    {
        "title": "Group Anagrams",
        "difficulty": "medium",
        "problem_statement": "Given an array of strings strs, group the anagrams together. You can return the answer in any order.\n\nAn Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.",
        "constraints": "1 <= strs.length <= 10^4\n0 <= strs[i].length <= 100\nstrs[i] consists of lowercase English letters.",
        "input_format": "Space-separated strings",
        "output_format": "Groups of anagrams, one group per line, words within group sorted alphabetically, groups sorted by first word",
        "sample_input_1": "eat tea tan ate nat bat",
        "sample_output_1": "ate eat tea\nbat\nnat tan",
        "sample_input_2": "a",
        "sample_output_2": "a",
        "test_cases": json.dumps([
            {"input": "eat tea tan ate nat bat", "expected_output": "ate eat tea\nbat\nnat tan"},
            {"input": "a", "expected_output": "a"},
            {"input": "", "expected_output": ""},
        ]),
        "tags": json.dumps(["hash-table", "string", "sorting"]),
    },
    {
        "title": "Jump Game",
        "difficulty": "medium",
        "problem_statement": "You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.\n\nReturn true if you can reach the last index, or false otherwise.",
        "constraints": "1 <= nums.length <= 10^4\n0 <= nums[i] <= 10^5",
        "input_format": "Space-separated integers",
        "output_format": "true or false",
        "sample_input_1": "2 3 1 1 4",
        "sample_output_1": "true",
        "sample_input_2": "3 2 1 0 4",
        "sample_output_2": "false",
        "test_cases": json.dumps([
            {"input": "2 3 1 1 4", "expected_output": "true"},
            {"input": "3 2 1 0 4", "expected_output": "false"},
            {"input": "0", "expected_output": "true"},
            {"input": "1 0 0", "expected_output": "false"},
        ]),
        "tags": json.dumps(["array", "dynamic-programming", "greedy"]),
    },
    {
        "title": "Median of Two Sorted Arrays",
        "difficulty": "hard",
        "problem_statement": "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\n\nThe overall run time complexity should be O(log (m+n)).",
        "constraints": "nums1.length == m\nnums2.length == n\n0 <= m <= 1000\n0 <= n <= 1000\n1 <= m + n <= 2000\n-10^6 <= nums1[i], nums2[i] <= 10^6",
        "input_format": "First line: space-separated integers (nums1)\nSecond line: space-separated integers (nums2)",
        "output_format": "The median as a float (one decimal place)",
        "sample_input_1": "1 3\n2",
        "sample_output_1": "2.0",
        "sample_input_2": "1 2\n3 4",
        "sample_output_2": "2.5",
        "test_cases": json.dumps([
            {"input": "1 3\n2", "expected_output": "2.0"},
            {"input": "1 2\n3 4", "expected_output": "2.5"},
            {"input": "0 0\n0 0", "expected_output": "0.0"},
            {"input": "\n1", "expected_output": "1.0"},
        ]),
        "tags": json.dumps(["array", "binary-search", "divide-and-conquer"]),
    },
    {
        "title": "Trapping Rain Water",
        "difficulty": "hard",
        "problem_statement": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
        "constraints": "n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5",
        "input_format": "Space-separated integers (heights)",
        "output_format": "A single integer (total water trapped)",
        "sample_input_1": "0 1 0 2 1 0 1 3 2 1 2 1",
        "sample_output_1": "6",
        "sample_input_2": "4 2 0 3 2 5",
        "sample_output_2": "9",
        "test_cases": json.dumps([
            {"input": "0 1 0 2 1 0 1 3 2 1 2 1", "expected_output": "6"},
            {"input": "4 2 0 3 2 5", "expected_output": "9"},
            {"input": "1 0 1", "expected_output": "1"},
            {"input": "3 0 2 0 4", "expected_output": "7"},
        ]),
        "tags": json.dumps(["array", "two-pointers", "dynamic-programming", "stack"]),
    },
    {
        "title": "Word Ladder",
        "difficulty": "hard",
        "problem_statement": "A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence beginWord -> s1 -> s2 -> ... -> sk such that:\n- Every adjacent pair of words differs by a single letter.\n- Every si for 1 <= i <= k is in wordList.\n- sk == endWord\n\nGiven two words, beginWord and endWord, and a dictionary wordList, return the number of words in the shortest transformation sequence from beginWord to endWord, or 0 if no such sequence exists.",
        "constraints": "1 <= beginWord.length <= 10\nendWord.length == beginWord.length\n1 <= wordList.length <= 5000\nwordList[i].length == beginWord.length\nAll words consist of lowercase English letters.\nAll words in wordList are unique.",
        "input_format": "First line: beginWord\nSecond line: endWord\nThird line: space-separated wordList",
        "output_format": "A single integer",
        "sample_input_1": "hit\ncog\nhot dot dog lot log cog",
        "sample_output_1": "5",
        "sample_input_2": "hit\ncog\nhot dot dog lot log",
        "sample_output_2": "0",
        "test_cases": json.dumps([
            {"input": "hit\ncog\nhot dot dog lot log cog", "expected_output": "5"},
            {"input": "hit\ncog\nhot dot dog lot log", "expected_output": "0"},
        ]),
        "tags": json.dumps(["hash-table", "string", "bfs"]),
    },
]

async def seed():
    async with AsyncSessionLocal() as db:
        for q in QUESTIONS:
            await db.execute(text("""
                INSERT INTO questions (title, difficulty, problem_statement, constraints,
                    input_format, output_format, sample_input_1, sample_output_1,
                    sample_input_2, sample_output_2, test_cases, tags, is_active)
                VALUES (:title, :difficulty, :problem_statement, :constraints,
                    :input_format, :output_format, :sample_input_1, :sample_output_1,
                    :sample_input_2, :sample_output_2, :test_cases::jsonb, :tags::jsonb, true)
                ON CONFLICT DO NOTHING
            """), {
                "title": q["title"],
                "difficulty": q["difficulty"],
                "problem_statement": q["problem_statement"],
                "constraints": q.get("constraints"),
                "input_format": q.get("input_format"),
                "output_format": q.get("output_format"),
                "sample_input_1": q.get("sample_input_1"),
                "sample_output_1": q.get("sample_output_1"),
                "sample_input_2": q.get("sample_input_2"),
                "sample_output_2": q.get("sample_output_2"),
                "test_cases": q.get("test_cases"),
                "tags": q.get("tags"),
            })
        await db.commit()
        print(f"Seeded {len(QUESTIONS)} questions successfully.")

if __name__ == "__main__":
    asyncio.run(seed())
